language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono:
  - 4.0.5
env:
  matrix:
    - CLI_VERSION=1.0.0-beta-002071
os:
  - linux
before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fiopenssl; fi
install:  
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -L --create-dirs https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.sh -o ./scripts/obtain/install.sh
  - find ./scripts -name "*.sh" -exec chmod +x {} \;
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
  # use bash to workaround bug https://github.com/dotnet/cli/issues/1725
  - sudo bash ./scripts/obtain/install.sh --channel "preview" --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR" --no-path
  # add dotnet to PATH
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
script: 
  - dotnet restore
  - cd Tests
  - dotnet build
  - dotnet test
