language: csharp
sudo: required
dist: trusty
dotnet: 1.0.0-preview2.1-003177
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono:
  - latest
os:
  - linux
script: 
  - cd Web
  - dotnet restore
  - dotnet build
  - cd ..
  - cd Tests
  - dotnet restore
  - dotnet build
  - dotnet test
