language: csharp
dotnet: 3.1.201
mono:
  - latest
os:
  - linux
dist: xenial
script: 
  - dotnet restore entity-framework-studies.sln
  - dotnet build entity-framework-studies.sln
  - dotnet test tests/Tests
  - dotnet test tests/FsTests
branches:
  only:
    - master
    - dotnetcore
