language: csharp
dotnet: 2.2
mono:
  - latest
os:
  - linux
script: 
  - dotnet restore entity-framework-studies.sln
  - dotnet build entity-framework-studies.sln
  - dotnet test tests/Tests
  - dotnet test tests/FsTests
branches:
  only:
    - master
    - dotnetcore
