language: csharp
sudo: false
dist: trusty
dotnet: 1.0.0-preview2.1-003177
mono:
  - latest
os:
  - linux
script: 
  - cd Web
  - dotnet restore
  - dotnet build
  - cd ..
  - cd Tests
  - dotnet restore
  - dotnet build
  - dotnet test
