language: csharp
dotnet: 1.0.0-preview2-003156

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      mono: latest

script: 
  - dotnet restore
  - cd Web
  - dotnet build
  - cd ..
  - cd Tests
  - dotnet build
  - dotnet test
