language: csharp
matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      
sudo: false 

script: 
  - dotnet restore
  - cd Web
  - dotnet build
  - cd ..
  - cd Tests
  - dotnet build
  - dotnet test
