
version: "3.4"
services:

  webf-migrations:
    build:
      context: migrations/FsMigrations
      dockerfile: Dockerfile
    environment:
      PASSWORD: "EF_test_PASSWORD123"
      SERVER: "db"
      DATABASE: "ef_core_studies_fsharp"
    depends_on:
      - db

  db:
    build:
      context: ./db/
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "EF_test_PASSWORD123"
      ACCEPT_EULA: "Y"
