version: "3.4"
services:
  webc:
    build:
      context: src/Web
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionStrings__DefaultConnection: ${Web__DefaultConnection}
    ports:
      - "8000:80"
    depends_on:
      - db
  webf:
    build:
      context: src/WebFs
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionStrings__DefaultConnection: ${WebFs__DefaultConnection}
    ports:
      - "8001:80"
    depends_on:
      - db
      - webf-migrations
  webf-migrations:
    build:
      context: migrations/FsMigrations
      dockerfile: Dockerfile
    environment:
      PASSWORD: ${SA_PASSWORD}
      SERVER: "db"
      DATABASE: "ef_core_studies_fsharp"
    depends_on:
      - db
