
version: "3.4"
services:

  db:
    build:
      context: ./db/
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
